version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      aws-cdk:
        patterns:
          - aws-cdk-lib
          - constructs
          - "@aws-cdk/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
